export const ACTION_TYPE_SHOW_DRAWER = 'ACTION_TYPE_SHOW_LEFT_DRAWER';
export const ACTION_TYPE_HIDE_DRAWER = 'ACTION_TYPE_HIDE_LEFT_DRAWER';
export const ACTION_TYPE_TOGGLE_MENU = 'ACTION_TYPE_TOGGLE_MENU';
export const ACTION_TYPE_UPDATE_DATA = 'ACTION_TYPE_UPDATE_DATA';
export const ACTION_TYPE_POI_TAG_VISIBILITY = 'ACTION_TYPE_POI_TAG_VISIBILITY';
export const ACTION_TYPE_UPDATE_WALLET = 'ACTION_TYPE_UPDATE_WALLET';
export const ACTION_TYPE_TOGGLE_THEME = 'ACTION_TYPE_TOGGLE_THEME';
export const ACTION_TYPE_IS_MOBILE = 'ACTION_TYPE_IS_MOBILE';
