export const ACTION_TYPE_SET_MAP_VIEWPORT = 'ACTION_TYPE_SET_MAP_VIEWPORT';
export const ACTION_TYPE_SHOW_DRAWER = 'ACTION_TYPE_SHOW_LEFT_DRAWER';
export const ACTION_TYPE_HIDE_DRAWER = 'ACTION_TYPE_HIDE_LEFT_DRAWER';
export const ACTION_TYPE_TOGGLE_MENU = 'ACTION_TYPE_TOGGLE_MENU';
export const ACTION_TYPE_TOGGLE_LAYER_VISIBILITY =
  'ACTION_TYPE_TOGGLE_LAYER_VISIBILITY';
export const ACTION_TYPE_UPDATE_LAYERS_DATA = 'ACTION_TYPE_UPDATE_LAYERS_DATA';
export const ACTION_TYPE_POI_TAG_VISIBILITY = 'ACTION_TYPE_POI_TAG_VISIBILITY';
